mysql:
  path: 127.0.0.1
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: explemwebsite
  username: root
  password: "123456"
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
zap:
  level: info
  format: console
  prefix: '[ys/service]'
  director: log
  showLine: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: yyPlus
  signing-key: 16eb927e-9710-43cb-b03d-d253e0fb8bc3